server:
  port: 8081

spring:
  application:
    name: datateam

  datasource:
    url: jdbc:postgresql://localhost:5433/datateamprueba
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update